### ISSUE TITLE
add example using nginx

### ISSUE THREAD

**Issue by tomkralidis** [cartologic/pygeoapi-auth#1]
It would be valuable to have an optional example demonstrating nginx integration (e.g. commented out in `docker-compose.yml`) in addition to the default Caddy setup.

cc @Youssef-Harby

**Comment by yharby** [comment]
Hi @tomkralidis, sure I will add a nginx integration

**Comment by yharby** [comment]
Hi @tomkralidis,

I've added a basic Nginx integration example. Could you please review and test it?
